# Generated by Django 4.2.4 on 2023-10-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_paying_options_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='created_at',
        ),
    ]
