# Generated by Django 4.2.4 on 2023-11-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
