# Generated by Django 4.2.4 on 2023-12-01 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_ordereditem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img'),
            preserve_default=False,
        ),
    ]
